coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        threshold: 0.64%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        if_ci_failed: error

codecov:
  require_ci_to_pass: false
