import { IBundle } from '@smile-cdr/fhirts/dist/FHIR-R4/interfaces/IBundle';

export const userFixtures = [
  {
    id: '081724e8-5fc1-47dd-8d0c-fa0c6ae6ddf0',
    createdTimestamp: 1649070783732,
    username: 'april4petertest',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'april4',
    lastName: 'petertest',
    attributes: { contact: ['0000000000'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '7f5d1800-e1c2-4c31-b01d-d084b8c96bb0',
    createdTimestamp: 1648720529065,
    username: 'blue',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Blue',
    lastName: 'Test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '40fe3724-95e3-48cb-b90a-f67aebcf4120',
    createdTimestamp: 1634817468769,
    username: 'chw_demo_user',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Chw',
    lastName: 'User',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '46bccd72-0505-487b-a208-9a4d2c4e033c',
    createdTimestamp: 1641990763482,
    username: 'codademo',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'John',
    lastName: 'Coda',
    attributes: { organization: ['105'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 1644337122,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '718d900b-74ee-43ed-b075-3acc4e344fea',
    createdTimestamp: 1642068942483,
    username: 'codademo2',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Jane',
    lastName: 'Coda',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '2bc763f7-1d3a-41e2-89b2-3faed13f655c',
    createdTimestamp: 1643973454844,
    username: 'codasprint2',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Roy',
    lastName: 'Munge',
    email: 'rMunge@munge.mars',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: 'c6a68722-a5b4-4f84-bd79-97ef1a5aed9d',
    createdTimestamp: 1636013859425,
    username: 'covax',
    enabled: true,
    totp: false,
    emailVerified: true,
    firstName: 'Covax',
    lastName: 'Demo',
    email: 'demo@demo.mars',
    attributes: { questionnaire_publisher: ['covax'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '0ce824e1-6701-4d0b-bd31-42fbf1a057b8',
    createdTimestamp: 1645701700130,
    username: 'crvs',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'CRVS',
    lastName: 'User',
    email: 'crvsdemo@demo.mars',
    attributes: { questionnaire_publisher: ['crvs'], organization: ['361'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: 'b87ff3c2-cbc6-43e6-b753-a9620756f9e4',
    createdTimestamp: 1621324260170,
    username: 'demo',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Demo',
    lastName: '26195',
    attributes: { organization: ['105'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 1638793376,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '9ed39e30-3350-4625-8943-47e611fb1dcf',
    createdTimestamp: 1648820960292,
    username: 'ecbis',
    enabled: true,
    totp: false,
    emailVerified: true,
    attributes: { organization: ['362'] },
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '39c5247d-c7ea-4682-b8c1-201119e5b445',
    createdTimestamp: 1647000027425,
    username: 'ecbis_cha',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'eCBIS',
    lastName: 'CHA',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '7a693a5e-1622-423d-9e1d-9c4d4ef2e74a',
    createdTimestamp: 1643034870504,
    username: 'ecbis_user',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'ECBIS ',
    lastName: 'Test Yser',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: '75cdf818-81fd-4df9-b3f8-fb03931d25f6',
    createdTimestamp: 1647464153612,
    username: 'endpoints',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'Practitioner',
    lastName: 'Endpoint',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: 'db20abd6-e8a3-4161-a340-66077d19a1e4',
    createdTimestamp: 1631807968051,
    username: 'est',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'test404',
    lastName: 'estse101',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
  {
    id: 'b79e5f2d-37de-4c7e-9b3d-4341bf62ad78',
    createdTimestamp: 1646297153142,
    username: 'fghj',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'testhh',
    lastName: 'thg',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
    access: {
      manageGroupMembership: true,
      view: true,
      mapRoles: true,
      impersonate: false,
      manage: true,
    },
  },
];

export const practitioner = {
  resourceType: 'Bundle',
  id: '00ce53e7-a282-4d82-b623-31973b8d1e57',
  meta: {
    lastUpdated: '2022-04-12T13:08:26.202+00:00',
  },
  type: 'searchset',
  total: 1,
  link: [
    {
      relation: 'self',
      url: 'https://fhir.labs.smartregister.org:443/fhir/Practitioner/_search?_format=json&name%3Acontains=Allan',
    },
  ],
  entry: [
    {
      fullUrl: 'https://fhir.labs.smartregister.org:443/fhir/Practitioner/206',
      resource: {
        resourceType: 'Practitioner',
        id: '206',
        meta: {
          versionId: '2',
          lastUpdated: '2021-09-14T07:37:31.213+00:00',
          source: '#74cc383a67268f33',
        },
        identifier: [
          {
            use: 'official',
            value: 'c1d36d9a-b771-410b-959e-af2c04d132a2',
          },
          {
            use: 'secondary',
          },
        ],
        active: false,
        name: [
          {
            use: 'official',
            family: 'Allan',
            given: ['Allay'],
          },
        ],
        telecom: [
          {
            system: 'email',
          },
        ],
      },
      search: {
        mode: 'match',
      },
    },
  ],
} as unknown as IBundle;

export const careTeams = {
  resourceType: 'Bundle',
  id: '487d4351-c29e-403c-9477-fa4b583f8d31',
  meta: {
    lastUpdated: '2022-04-12T13:06:48.376+00:00',
  },
  type: 'searchset',
  total: 1,
  link: [
    {
      relation: 'self',
      url: 'https://fhir.labs.smartregister.org:443/fhir/CareTeam/_search?_format=json&participant%3Apractitioner=206',
    },
  ],
  entry: [
    {
      fullUrl: 'https://fhir.labs.smartregister.org:443/fhir/CareTeam/325',
      resource: {
        resourceType: 'CareTeam',
        id: '325',
        meta: {
          versionId: '4',
          lastUpdated: '2021-09-22T15:16:54.461+00:00',
          source: '#1963eef255fe3b4e',
        },
        identifier: [
          {
            use: 'official',
            value: '106440c4-e1ad-45ec-8437-e0c8cceac882',
          },
        ],
        status: 'active',
        name: 'Care Team Three Three',
        subject: {
          reference: 'Group/306',
          display: 'ANC patients',
        },
        participant: [
          {
            member: {
              reference: 'Practitioner/206',
            },
          },
          {
            member: {
              reference: 'Practitioner/213',
              display: 'Bobi mapesa',
            },
          },
        ],
      },
      search: {
        mode: 'match',
      },
    },
  ],
};

export const group = {
  resourceType: 'Bundle',
  id: 'f20c0276-8364-4e31-ae99-e4bcdb3813ce',
  meta: {
    lastUpdated: '2022-10-14T01:43:51.928+00:00',
  },
  type: 'searchset',
  total: 1,
  link: [
    {
      relation: 'self',
      url: 'https://fhir.labs.smartregister.org:443/fhir/Group/_search?identifier=cab07278-c77b-4bc7-b154-bcbf01b7d35b',
    },
  ],
  entry: [
    {
      fullUrl:
        'https://fhir.labs.smartregister.org:443/fhir/Group/acb9d47e-7247-448f-be93-7a193a5312da',
      resource: {
        resourceType: 'Group',
        id: 'acb9d47e-7247-448f-be93-7a193a5312da',
        meta: {
          versionId: '2',
          lastUpdated: '2022-10-14T01:40:59.365+00:00',
          source: '#9a5be796c77bd270',
        },
        identifier: [
          {
            use: 'official',
            value: 'acb9d47e-7247-448f-be93-7a193a5312da',
          },
          {
            use: 'secondary',
            value: 'cab07278-c77b-4bc7-b154-bcbf01b7d35b',
          },
        ],
        active: true,
        type: 'practitioner',
        actual: true,
        code: {
          coding: [
            {
              system: 'http://snomed.info/sct',
              code: '405623001',
              display: 'Assigned practitioner',
            },
          ],
        },
        name: 'Demoflotus kenyaplotus',
        member: [
          {
            entity: {
              reference: 'Practitioner/206',
            },
          },
        ],
      },
      search: {
        mode: 'match',
      },
    },
  ],
};
