// Error
export const ERROR_PRODUCT_NAME_REQUIRED = 'Product is required';
export const ERROR_DELIVERY_DATE_REQUIRED = 'Delivery date is required';
export const ERROR_ACCOUNTABILITY_DATE_REQUIRED = 'Accountability end date is required';
export const ERROR_UNICEF_SECTION_REQUIRED = 'UNICEF section is required';
export const ERROR_PO_NUMBER_REQUIRED = 'PO number is required';

// Rendered text
export const ADD_SERVICE_POINT = '+ Add service point';
export const SERVICE_POINT_INVENTORY = 'Service point inventory';
export const SERVICE_POINT_TH = 'Service point';
export const TYPE_TH = 'type';
export const LOCATION_TH = 'Location';
export const SERVICE_POINT_ID_TH = 'Service point ID';
export const ACTIONS_TH = 'Actions';
export const VIEW = 'view';
export const FETCHING_LOCATIONS = 'Fetching locations';
export const FETCHING_LOCATIONS_DESCRIPTION = 'Please wait, while locations are being fetched';
export const LOADING_ELLIPSIS = 'Loading ...';
export const ADD_INVENTORY_ITEM = 'Add inventory item';
export const CANCEL = 'Cancel';
export const SAVE = 'Save';
export const SAVING = 'Saving';
export const OPTIONAL = 'optional';
export const QUANTITY = 'Quantity';
export const DELIVERY_DATE = 'Delivery date';
export const ACCOUNTABILITY_END_DATE = 'Accountability end date';
export const UNICEF_SECTION = 'UNICEF section';
export const DONOR = 'Donor';
export const PO_NUMBER = 'PO number';
export const SELECT = 'Select';
export const HEALTH = 'Health';
export const WASH = 'Wash';
export const NUTRITION = 'Nutrition';
export const EDUCATION = 'Education';
export const CHILD_PROTECTION = 'Child protection';
export const SOCIAL_POLICY = 'Social policy';
export const C4D = 'C4D';
export const DRR = 'DRR';
