export const eusmServicePoint = {
  resourceType: 'ValueSet',
  id: 'eusm-other-service-point',
  meta: {
    extension: [
      {
        url: 'http://hapifhir.io/fhir/StructureDefinition/valueset-expansion-message',
        valueString:
          'ValueSet "ValueSet.url[http://smartregister.org/ValueSet/eusm-other-service-point]" has not yet been pre-expanded. Performing in-memory expansion without parameters. Current status: NOT_EXPANDED | The ValueSet is waiting to be picked up and pre-expanded by a scheduled task.',
      },
    ],
    versionId: '1',
  },
  url: 'http://smartregister.org/ValueSet/eusm-other-service-point',
  status: 'active',
  compose: {
    include: [
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
      },
    ],
  },
  expansion: {
    identifier: '484544d9-bbd5-4d6f-bea0-edad80d33bab',
    timestamp: '2024-03-11T12:29:26+00:00',
    total: 40,
    offset: 0,
    parameter: [
      {
        name: 'offset',
        valueInteger: 0,
      },
      {
        name: 'count',
        valueInteger: 1000,
      },
    ],
    contains: [
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Switzerland',
        display: 'NatCom Switzerland',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Germany',
        display: 'NatCom Germany',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'USAID FFP',
        display: 'USAID FFP',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Denmark',
        display: 'NatCom Denmark',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom France',
        display: 'NatCom France',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Japan',
        display: 'NatCom Japan',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Luxembourg',
        display: 'NatCom Luxembourg',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of UK',
        display: 'Govt of UK',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Nutrition International',
        display: 'Nutrition International',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Monaco',
        display: 'Monaco',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Canada',
        display: 'NatCom Canada',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'UNICEF',
        display: 'UNICEF',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'GAVI',
        display: 'GAVI',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'ADB',
        display: 'ADB',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom USA',
        display: 'NatCom USA',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Poland',
        display: 'NatCom Poland',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of Canada',
        display: 'Govt of Canada',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Iceland',
        display: 'NatCom Iceland',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Spain',
        display: 'NatCom Spain',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Finland',
        display: 'NatCom Finland',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of Germany',
        display: 'Govt of Germany',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Norway',
        display: 'NatCom Norway',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Italy',
        display: 'NatCom Italy',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Sweden',
        display: 'NatCom Sweden',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of Korea',
        display: 'Govt of Korea',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'World Bank',
        display: 'World Bank',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'End Violence Fund',
        display: 'End Violence Fund',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom UK',
        display: 'NatCom UK',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Netherlands',
        display: 'NatCom Netherlands',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'BMGF',
        display: 'BMGF',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'NatCom Belgium',
        display: 'NatCom Belgium',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'ECW',
        display: 'ECW',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'OFDA',
        display: 'OFDA',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of Japan',
        display: 'Govt of Japan',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'ECHO',
        display: 'ECHO',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of Norway',
        display: 'Govt of Norway',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'EC',
        display: 'EC',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'CDC',
        display: 'CDC',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'Govt of France',
        display: 'Govt of France',
      },
      {
        system: 'http://smartregister.org/CodeSystem/eusm-donors',
        version: '1.0',
        code: 'USAID',
        display: 'USAID',
      },
    ],
  },
};
