---
name: General OpenSRP web FHIR.
about: Use this to Create issues the are FHIR related.
title: '[FHIR Road Map] '
labels: FHIR compatibility
assignees: ''
---

## Issue Description

## Resources

### FHIR Resources to reference

## Please share any other relevant information about the change request

---

Remember:

1. To alert the team in the [#opensrp-web](https://onaio.slack.com/archives/C01R82Y9N58) channel.
2. To follow up on delivery. You're in-charge.
