import { generateQResponseModel, _createLinkIdItemMap } from "../converter";
import { sampleCovidQ } from "../fixtures/Q";

describe("converter utils", () => {
  xit("generates response model correctly", () => {
    const response = generateQResponseModel(sampleCovidQ);
    expect(response).toEqual(undefined);
  });

  it("flattens the questionnaire when creating linkItem map", () => {
    const response = _createLinkIdItemMap(sampleCovidQ);
    expect(JSON.stringify(response)).toEqual({
      meta: {
        profile: [
          "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|2.7",
        ],
        tag: [{ display: "lformsVersion: 21.2.1" }],
      },
      date: "2020-04-11T22:01:37.262Z",
      version: "1",
      subjectType: ["Organization"],
      status: "draft",
      experimental: true,
      publisher: "Health eData Inc",
      description: "Healthcare Worker Staffing Pathway",
      copyright:
        "Content source: Centers for Disease Control and Prevention , National Center for Emerging and Zoonotic Infectious Diseases (NCEZID) , Division of Healthcare Quality Promotion (DHQP)",
      url: "http://example.org/healthcareworkerstaffingpathway",
      name: "HealthcareWorkerStaffingPathway",
      title: "Healthcare Worker Staffing Pathway",
      type: "array",
      items: [
        {
          type: "object",
          dataType: "SECTION",
          properties: [
            {
              dataType: "ST",
              properties: [],
              prefix: "1",
              text: "Facility ID",
              codeList: [
                { code: "Q1", display: "Facility ID", system: "Custom" },
              ],
              questionCode: "Q1",
              questionCodeSystem: "Custom",
              linkId: "/G1/Q1",
              questionCardinality: { max: "1", min: "1" },
              answerCardinality: { min: "1" },
              codingInstructions:
                "The NHSN-assigned facility ID will be autoentered by the computer.",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "The NHSN-assigned facility ID will be autoentered by the computer.",
            },
            {
              dataType: "ST",
              properties: [],
              prefix: "2",
              text: "Summary Census #ID",
              codeList: [
                { code: "Q2", display: "Summary Census #ID", system: "Custom" },
              ],
              questionCode: "Q2",
              questionCodeSystem: "Custom",
              linkId: "/G1/Q2",
              readOnly: true,
              questionCardinality: { max: "1", min: "1" },
              answerCardinality: { min: "1" },
              codingInstructions: "Auto-generated by the computer.",
              codingInstructionsFormat: "text",
              codingInstructionsPlain: "Auto-generated by the computer.",
            },
            {
              dataType: "DT",
              properties: [],
              prefix: "3",
              text: "Effective Date",
              codeList: [
                { code: "Q3", display: "Effective Date", system: "Custom" },
              ],
              questionCode: "Q3",
              questionCodeSystem: "Custom",
              linkId: "/G1/Q3",
              questionCardinality: { max: "1", min: "1" },
              answerCardinality: { min: "1" },
              codingInstructions:
                "Required. Select the date for which the recorded data was collected for the following questions.",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "Required. Select the date for which the recorded data was collected for the following questions.",
            },
          ],
          text: "Facility MetaData",
          codeList: [
            { code: "G1", display: "Facility MetaData", system: "Custom" },
          ],
          questionCode: "G1",
          questionCodeSystem: "Custom",
          linkId: "/G1",
          questionCardinality: { max: "1", min: "1" },
        },
        {
          dataType: "SECTION",
          properties: [
            {
              dataType: "TITLE",
              properties: {},
              text: "Does your organization consider that it has a critical staffing shortage in this group today? (Check appropriate box if answer is Yes)",
              questionCode: "D1",
              questionCodeSystem: "LinkId",
              linkId: "/G2/D1",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "1",
              text: "Environmental services",
              codeList: [
                {
                  code: "Q1",
                  display: "Environmental services",
                  system: "Custom",
                },
              ],
              questionCode: "Q1",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q1",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "2",
              text: "Nurses",
              codeList: [{ code: "Q2", display: "Nurses", system: "Custom" }],
              questionCode: "Q2",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q2",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "registered nurses and licensed practical nurses",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "registered nurses and licensed practical nurses",
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "3",
              text: "Respiratory therapists",
              codeList: [
                {
                  code: "Q3",
                  display: "Respiratory therapists",
                  system: "Custom",
                },
              ],
              questionCode: "Q3",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q3",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "4",
              text: "Pharmacists and pharmacy techs",
              codeList: [
                {
                  code: "Q4",
                  display: "Pharmacists and pharmacy techs",
                  system: "Custom",
                },
              ],
              questionCode: "Q4",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q4",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "5",
              text: "Physicians",
              codeList: [
                { code: "Q5", display: "Physicians", system: "Custom" },
              ],
              questionCode: "Q5",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q5",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions: "attending physicians, fellows",
              codingInstructionsFormat: "text",
              codingInstructionsPlain: "attending physicians, fellows",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "6",
              text: "Other licensed independent practitioners",
              codeList: [
                {
                  code: "Q6",
                  display: "Other licensed independent practitioners",
                  system: "Custom",
                },
              ],
              questionCode: "Q6",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q6",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "advanced practice nurses, physician assistants",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "advanced practice nurses, physician assistants",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "7",
              text: "Temporary physicians, nurses, respiratory therapists, and pharmacists",
              codeList: [
                {
                  code: "Q7",
                  display:
                    "Temporary physicians, nurses, respiratory therapists, and pharmacists",
                  system: "Custom",
                },
              ],
              questionCode: "Q7",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q7",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "Includes “per diems,” “travelers,” retired, or other seasonal or intermittently contracted persons",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "Includes “per diems,” “travelers,” retired, or other seasonal or intermittently contracted persons",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "8",
              text: "Other HCP†",
              codeList: [
                { code: "Q8", display: "Other HCP†", system: "Custom" },
              ],
              questionCode: "Q8",
              questionCodeSystem: "Custom",
              linkId: "/G2/Q8",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "Persons who work in the facility, regardless of clinical responsibility or patient contact not included in categories above. †Healthcare Personnel (HCP) is the plural of healthcare worker",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "Persons who work in the facility, regardless of clinical responsibility or patient contact not included in categories above. †Healthcare Personnel (HCP) is the plural of healthcare worker",
            },
          ],
          prefix: "2",
          text: "Critical Staffing Shortage Today",
          codeList: [
            {
              code: "G2",
              display: "Critical Staffing Shortage Today",
              system: "Custom",
            },
          ],
          questionCode: "G2",
          questionCodeSystem: "Custom",
          linkId: "/G2",
          questionCardinality: { max: "1", min: "1" },
        },
        {
          dataType: "SECTION",
          properties: [
            {
              dataType: "TITLE",
              properties: {},
              text: "Does your organization consider that it has a critical staffing shortage in this group within one week? (Check appropriate box if answer is Yes)",
              questionCode: "D1",
              questionCodeSystem: "LinkId",
              linkId: "/G3/D1",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "1",
              text: "Environmental services",
              codeList: [
                {
                  code: "Q1",
                  display: "Environmental services",
                  system: "Custom",
                },
              ],
              questionCode: "Q1",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q1",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "2",
              text: "Nurses",
              codeList: [{ code: "Q2", display: "Nurses", system: "Custom" }],
              questionCode: "Q2",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q2",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "registered nurses and licensed practical nurses",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "registered nurses and licensed practical nurses",
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "3",
              text: "Respiratory therapists",
              codeList: [
                {
                  code: "Q3",
                  display: "Respiratory therapists",
                  system: "Custom",
                },
              ],
              questionCode: "Q3",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q3",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: {},
              prefix: "4",
              text: "Pharmacists and pharmacy techs",
              codeList: [
                {
                  code: "Q4",
                  display: "Pharmacists and pharmacy techs",
                  system: "Custom",
                },
              ],
              questionCode: "Q4",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q4",
              questionCardinality: { max: "1", min: "1" },
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "5",
              text: "Physicians",
              codeList: [
                { code: "Q5", display: "Physicians", system: "Custom" },
              ],
              questionCode: "Q5",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q5",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions: "attending physicians, fellows",
              codingInstructionsFormat: "text",
              codingInstructionsPlain: "attending physicians, fellows",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "6",
              text: "Other licensed independent practitioners",
              codeList: [
                {
                  code: "Q6",
                  display: "Other licensed independent practitioners",
                  system: "Custom",
                },
              ],
              questionCode: "Q6",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q6",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "advanced practice nurses, physician assistants",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "advanced practice nurses, physician assistants",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "7",
              text: "Temporary physicians, nurses, respiratory therapists, and pharmacists",
              codeList: [
                {
                  code: "Q7",
                  display:
                    "Temporary physicians, nurses, respiratory therapists, and pharmacists",
                  system: "Custom",
                },
              ],
              questionCode: "Q7",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q7",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "Includes “per diems,” “travelers,” retired, or other seasonal or intermittently contracted persons",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "Includes “per diems,” “travelers,” retired, or other seasonal or intermittently contracted persons",
            },
            {
              dataType: "BL",
              properties: [],
              prefix: "8",
              text: "Other HCP†",
              codeList: [
                { code: "Q8", display: "Other HCP†", system: "Custom" },
              ],
              questionCode: "Q8",
              questionCodeSystem: "Custom",
              linkId: "/G3/Q8",
              questionCardinality: { max: "1", min: "1" },
              codingInstructions:
                "Persons who work in the facility, regardless of clinical responsibility or patient contact not included in categories above. †Healthcare Personnel (HCP) is the plural of healthcare worker",
              codingInstructionsFormat: "text",
              codingInstructionsPlain:
                "Persons who work in the facility, regardless of clinical responsibility or patient contact not included in categories above. †Healthcare Personnel (HCP) is the plural of healthcare worker",
            },
          ],
          prefix: "3",
          text: "Critical Staffing Shortage Within One Week",
          codeList: [
            {
              code: "G3",
              display: "Critical Staffing Shortage Within One Week",
              system: "Custom",
            },
          ],
          questionCode: "G3",
          questionCodeSystem: "Custom",
          linkId: "/G3",
          questionCardinality: { max: "1", min: "1" },
        },
      ],
      fhirVersion: "R4",
    });
  });
});
