import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  optimizeDeps: {
    include: ['@opensrp/notifications',
      "@opensrp/error-boundary-fallback",
      "@opensrp/fhir-care-team",
      "@opensrp/fhir-client",
      "@opensrp/fhir-group-management",
      "@opensrp/fhir-healthcare-service",
      "@opensrp/fhir-user-management",
      "@opensrp/fhir-location-management",
      "@opensrp/fhir-quest-form",
      "@opensrp/fhir-resources",
      "@opensrp/fhir-team-management",
      "@opensrp/fhir-views",
      "@opensrp/i18n",
      "@opensrp/keycloak-service",
      "@opensrp/user-management",
      "@opensrp/location-management",
      "@opensrp/notifications",
      "@opensrp/reducer-factory",
      "@opensrp/server-service",
      "@opensrp/store",
      "@opensrp/pkg-config",
      "@opensrp/rbac",
      "@opensrp/react-utils",
      "@opensrp/server-logout",
      "@opensrp/template",
    ],
  },
  build: {
    commonjsOptions: {
      include: [
        /notifications/,
        /error-boundary-fallback/,
        /fhir-care-team/,
        /fhir-client/,
        /fhir-group-management/,
        /fhir-healthcare-service/,
        /fhir-user-management/,
        /fhir-location-management/,
        /fhir-quest-form/,
        /fhir-resources/,
        /fhir-team-management/,
        /fhir-views/,
        /i18n/,
        /keycloak-service/,
        /user-management/,
        /location-management/,
        /notifications/,
        /reducer-factory/,
        /server-service/,
        /store/,
        /pkg-config/,
        /rbac/,
        /react-utils/,
        /server-logout/,
        /template/,
        /node_modules/],
    },
  },
})
