import type { IQuestionnaire } from '@smile-cdr/fhirts/dist/FHIR-R4/interfaces/IQuestionnaire';

export const openChoiceQuest = {
  date: '2020-04-11T22:01:37.262Z',
  version: '1',
  status: 'draft',
  experimental: true,
  url: 'http://example.org/foodQuestions',
  name: 'foodQuestions',
  title: 'Food questions',
  resourceType: 'Questionnaire',
  item: [
    {
      type: 'choice',
      code: [
        {
          code: 'Q4',
          display: 'What pizza toppings would you like?',
          system: 'Custom',
        },
      ],
      required: true,
      linkId: '/G1/Q4',
      text: 'What pizza toppings would you like?',
      prefix: '4',
      repeats: true,
      answerOption: [
        {
          valueString: 'Cheese',
        },
        {
          valueString: 'Ham',
        },
        {
          valueString: 'Mushrooms',
        },
      ],
      item: [
        {
          text: 'Favorite toppings',
          type: 'display',
          linkId: '/G1/Q4-help',
          extension: [
            {
              url: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
              valueCodeableConcept: {
                text: 'Help-Button',
                coding: [
                  {
                    code: 'help',
                    display: 'Help-Button',
                    system: 'http://hl7.org/fhir/questionnaire-item-control',
                  },
                ],
              },
            },
          ],
        },
      ],
    },
  ],
} as unknown as IQuestionnaire;

export const healthWorker = {
  meta: {
    profile: ['http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|2.7'],
    tag: [
      {
        display: 'lformsVersion: 21.2.1',
      },
    ],
  },
  date: '2020-04-11T22:01:37.262Z',
  lastReviewDate: '2020-04-11T22:01:37.262Z',
  effectivePeriod: {
    start: '2020-04-11T22:01:37.262Z',
    end: '2020-04-11T22:01:37.262Z',
  },
  version: '1',
  subjectType: ['Organization'],
  status: 'draft',
  experimental: true,
  publisher: 'Health eData Inc',
  description:
    'CDC’s NHSN is supporting the nation’s COVID-19 response by introducing a new COVID-19 Module. COVID-19 Module consists of 3 pathways  -  Patient Impact and Hospital Capacity Pathway, Healthcare Worker Staffing Pathway and Healthcare Supply Pathway The COVID-19 Module consists of three pathways within NHSN’s Patient Safety Component:  This Questionnaire represent the Healthcare Worker Staffing Pathway Module.  More information about this module can be found here: https://www.cdc.gov/nhsn/acute-care-hospital/covid19/index.html',
  copyright:
    'Content source: Centers for Disease Control and Prevention , National Center for Emerging and Zoonotic Infectious Diseases (NCEZID) , Division of Healthcare Quality Promotion (DHQP)',
  url: 'http://example.org/healthcareworkerstaffingpathway',
  name: 'HealthcareWorkerStaffingPathway',
  title: 'Healthcare Worker Staffing Pathway',
  resourceType: 'Questionnaire',
  item: [
    {
      type: 'group',
      code: [
        {
          code: 'G1',
          display: 'Facility MetaData',
          system: 'Custom',
        },
      ],
      required: false,
      linkId: '/G1',
      text: 'Facility MetaData',
      item: [
        {
          type: 'string',
          code: [
            {
              code: 'Q1',
              display: 'Facility ID',
              system: 'Custom',
            },
          ],
          required: true,
          linkId: '/G1/Q1',
          text: 'Facility ID',
          prefix: '1',
          item: [
            {
              text: 'The NHSN-assigned facility ID will be autoentered by the computer.',
              type: 'display',
              linkId: '/G1/Q1-help',
              extension: [
                {
                  url: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
                  valueCodeableConcept: {
                    text: 'Help-Button',
                    coding: [
                      {
                        code: 'help',
                        display: 'Help-Button',
                        system: 'http://hl7.org/fhir/questionnaire-item-control',
                      },
                    ],
                  },
                },
              ],
            },
          ],
        },
        {
          type: 'string',
          code: [
            {
              code: 'Q2',
              display: 'Summary Census #ID',
              system: 'Custom',
            },
          ],
          required: true,
          linkId: '/G1/Q2',
          text: 'Summary Census #ID',
          prefix: '2',
          readOnly: true,
          initial: [
            {
              valueString: '(Auto-generated by the computer)',
            },
          ],
          item: [
            {
              text: 'Auto-generated by the computer.',
              type: 'display',
              linkId: '/G1/Q2-help',
              extension: [
                {
                  url: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
                  valueCodeableConcept: {
                    text: 'Help-Button',
                    coding: [
                      {
                        code: 'help',
                        display: 'Help-Button',
                        system: 'http://hl7.org/fhir/questionnaire-item-control',
                      },
                    ],
                  },
                },
              ],
            },
          ],
        },
        {
          type: 'date',
          code: [
            {
              code: 'Q3',
              display: 'Effective Date',
              system: 'Custom',
            },
          ],
          required: true,
          linkId: '/G1/Q3',
          text: 'Effective Date',
          prefix: '3',
          item: [
            {
              text: 'Required. Select the date for which the recorded data was collected for the following questions.',
              type: 'display',
              linkId: '/G1/Q3-help',
              extension: [
                {
                  url: 'http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl',
                  valueCodeableConcept: {
                    text: 'Help-Button',
                    coding: [
                      {
                        code: 'help',
                        display: 'Help-Button',
                        system: 'http://hl7.org/fhir/questionnaire-item-control',
                      },
                    ],
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
} as unknown as IQuestionnaire;
