/* eslint-disable @typescript-eslint/camelcase */
import { Require } from '@opensrp/react-utils/dist/types';
import { Organization } from '../../../ducks/organizations';
import { Practitioner } from '../../../ducks/practitioners';
import { FormField } from '../Form';

export const accessToken = 'token';
export const opensrpBaseURL = 'https://opensrp-stage.smartregister.org/opensrp/rest/';
export const id = '258b4dec-79d3-546d-9c5c-f172aa7e03b0';

export const team: Require<Organization, 'active' | 'id'> = {
  id: '1',
  resourceType: 'Organization',
  identifier: [{ use: 'official', value: id }],
  active: true,
  name: 'Test Test Team',
};

export const practitioners: Practitioner[] = [
  {
    resourceType: 'Practitioner',
    id: '1',
    active: true,
    name: [{ text: 'prac two' }],
    identifier: [{ use: 'official', value: '1' }],
  },
  {
    resourceType: 'Practitioner',
    id: '2',
    active: false,
    name: [{ text: 'prac one' }],
    identifier: [{ use: 'official', value: '2' }],
  },
  {
    resourceType: 'Practitioner',
    id: '3',
    active: false,
    name: [{ text: 'prac one' }],
    identifier: [{ use: 'official', value: '3' }],
  },
  {
    resourceType: 'Practitioner',
    id: '4',
    active: false,
    name: [{ text: 'Practitioner Two' }],
    identifier: [{ use: 'official', value: '4' }],
  },
  {
    resourceType: 'Practitioner',
    id: '5',
    active: false,
    name: [{ text: 'Practitioner One' }],
    identifier: [{ use: 'official', value: '5' }],
  },
  {
    resourceType: 'Practitioner',
    id: '6',
    active: true,
    name: [{ text: 'Benjamin Mulyungi' }],
    identifier: [{ use: 'official', value: '6' }],
  },
  {
    resourceType: 'Practitioner',
    id: '7',
    active: true,
    name: [{ text: 'test admin' }],
    identifier: [{ use: 'official', value: '7' }],
  },
];

export const intialValue: FormField = {
  name: team.name,
  active: team.active,
  practitioners: practitioners.slice(0, 3).map((prac) => prac.id),
};

export const teamPost: Organization = {
  resourceType: 'Organization',
  id: '1',
  active: intialValue.active,
  identifier: [{ use: 'official', value: id }],
  name: intialValue.name,
};

export const teams: Organization[] = [
  {
    id: '1',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '1' }],
    active: true,
    name: 'Sample test Team',
  },
  {
    id: '2',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '2' }],
    active: true,
    name: 'Sample test Team',
  },
  {
    id: '3',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '3' }],
    active: true,
    name: 'Sample test Team',
  },
  {
    id: '4',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '4' }],
    active: true,
    name: 'Sample test Team',
  },
  {
    id: '5',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '5' }],
    active: true,
    name: 'test team 11',
  },
  {
    id: '6',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '6' }],
    active: true,
    name: 'sample test 1',
  },
  {
    id: '7',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '7' }],
    active: true,
    name: 'test team 1',
  },
  {
    id: '8',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '8' }],
    active: true,
    name: 'asdasd',
  },
  {
    id: '9',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '9' }],
    active: true,
    name: 'asdasd',
  },
  {
    id: '10',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '10' }],
    active: true,
    name: 'asdasd',
  },
  {
    id: '11',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '11' }],
    active: true,
    name: 'test again',
  },
  {
    id: '12',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '12' }],
    active: true,
    name: 'test again',
  },
  {
    id: '13',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '13' }],
    active: true,
    name: 'test again',
  },
  {
    id: '14',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '14' }],
    active: true,
    name: 'test',
  },
  {
    id: '15',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '15' }],
    active: true,
    name: 'test',
  },
  {
    id: '16',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '16' }],
    active: true,
    name: 'asd',
  },
  {
    id: '17',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '17' }],
    active: true,
    name: 'asd',
  },
  {
    id: '18',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '18' }],
    active: true,
    name: 'asd',
  },
  {
    id: '19',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '19' }],
    active: true,
    name: 'test',
  },
  {
    id: '20',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '20' }],
    active: true,
    name: 'test',
  },
  {
    id: '21',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '21' }],
    active: true,
    name: 'test new',
  },
  {
    id: '22',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '22' }],
    active: true,
    name: 'test new',
  },
  {
    id: '23',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '23' }],
    active: true,
    name: 'test',
  },
  {
    id: '24',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '24' }],
    active: true,
    name: 'test',
  },
  {
    id: '25',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '25' }],
    active: true,
    name: 'test new',
  },
  {
    id: '26',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '26' }],
    active: true,
    name: 'test new',
  },
  {
    id: '27',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '27' }],
    active: true,
    name: 'testing new',
  },
  {
    id: '28',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '28' }],
    active: true,
    name: '',
  },
  {
    id: '29',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '29' }],
    active: true,
    name: 'asd',
  },
  {
    id: '30',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '30' }],
    active: true,
    name: 'asd',
  },
  {
    id: '31',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '31' }],
    active: true,
    name: 'test',
  },
  {
    id: '32',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '32' }],
    active: true,
    name: '',
  },
  {
    id: '33',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '33' }],
    active: true,
    name: 'asd',
  },
  {
    id: '34',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '34' }],
    active: true,
    name: 'test',
  },
  {
    id: '35',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '35' }],
    active: true,
    name: 'test',
  },
  {
    id: '36',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '36' }],
    active: true,
    name: 'asd',
  },
  {
    id: '37',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '37' }],
    active: true,
    name: 'Sample test Team 2',
  },
  {
    id: '38',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '38' }],
    active: true,
    name: 'Sample test Team',
  },
  {
    id: '39',
    resourceType: 'Organization',
    identifier: [{ use: 'official', value: '39' }],
    active: true,
    name: 'Test Test Team',
  },
];
