describe('Location Unit Management', () => {
    it('log in with valid credentials', () => {
        const username = Cypress.env('username')
        const password = Cypress.env('password')
        cy.visit('/')
        cy.get('input[name="username"]').clear()
            .type(username)
        cy.get('input[name="password"]').type(password, { log: false })
        cy.get('#kc-login').click()     
    })

    it('User can search for a location', function () {
        cy.get('.ant-menu-submenu-title .anticon')
            .click()
        cy.get('.ant-menu-inline .ant-menu-submenu-title')
            .eq(2)
            .should('have.text', 'Locations')
            .click()
        cy.get('.ant-menu-item a[href="/admin/location/unit"]')
            .click()
        cy.get('input.ant-input.ant-input-lg')
            .type('Malawi')
            .focused()
            .clear()
        })

    it('User can add a location unit', function () {
        cy.get('div a[href="/admin/location/unit/add"]')
            .click()
        cy.get('.ant-select-selection-search')
            .eq(0)
            .click()
        cy.get('.ant-select-tree-list .ant-select-tree-treenode span[title="Kenya"]')
            .should('have.text', 'Kenya')
            .click( { timeout: 5000 } )
        cy.get('.ant-form-item-control-input #location-form_name')
            .type('Kitale')
        cy.get('.ant-radio-group .ant-radio')
            .eq(1)
            .click()
        cy.get('input#location-form_externalId.ant-input')
                .type('Featured')
        cy.get('.ant-form-item-control-input .ant-select-selector')
            .eq(2)
            .click()
        cy.get('div[label="Test"]')
            .click()
        cy.get('.ant-form-item-control-input .ant-select-selector')
            .eq(2)
            .click()
        cy.get('#location-form-submit-button')
            .click()
    })

    it('User can edit a location unit', function () {
        cy.get('table tbody tr:nth-child(1) td:nth-child(3) a')
            .click()
        cy.get('#location-form-submit-button')
            .click()
    })

    it('User can view location unit details', function () {
        cy.get('table tbody tr:nth-child(1) td:nth-child(3) button.ant-btn')
            .eq(1)
            .click()
        cy.get('.anticon.anticon-close')
            .click( { multiple: true } )
        cy.get('.pl-3 svg')
            .click()
    }) 
})
