export const schema = {
  meta: {
    profile: [
      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|2.7",
    ],
    tag: [{ display: "lformsVersion: 21.2.1" }],
  },
  date: "2020-04-11T22:01:37.262Z",
  version: "1",
  subjectType: ["Organization"],
  status: "draft",
  experimental: true,
  publisher: "Health eData Inc",
  description:
    "CDC’s NHSN is supporting the nation’s COVID-19 response by introducing a new COVID-19 Module. COVID-19 Module consists of 3 pathways  -  Patient Impact and Hospital Capacity Pathway, Healthcare Worker Staffing Pathway and Healthcare Supply Pathway The COVID-19 Module consists of three pathways within NHSN’s Patient Safety Component:  This Questionnaire represent the Healthcare Worker Staffing Pathway Module.  More information about this module can be found here: https://www.cdc.gov/nhsn/acute-care-hospital/covid19/index.html",
  copyright:
    "Content source: Centers for Disease Control and Prevention , National Center for Emerging and Zoonotic Infectious Diseases (NCEZID) , Division of Healthcare Quality Promotion (DHQP)",
  url: "http://example.org/healthcareworkerstaffingpathway",
  $id: "http://example.org/healthcareworkerstaffingpathway",
  name: "HealthcareWorkerStaffingPathway",
  title: "Healthcare Worker Staffing Pathway",
  type: "object",
  properties: {
    "/G1": {
      linkId: "/G1",
      type: "array",
      items: {
        type: "object",
        dataType: "SECTION",
        title: "Facility MetaData",
        codeList: [
          { code: "G1", display: "Facility MetaData", system: "Custom" },
        ],
        questionCode: "G1",
        questionCodeSystem: "Custom",
        questionCodeDisplay: "Facility MetaData",
        linkId: "/G1",
        properties: {
          "/G1/Q1": {
            type: "string",
            dataType: "ST",
            prefix: "1",
            title: "Facility ID",
            codeList: [
              { code: "Q1", display: "Facility ID", system: "Custom" },
            ],
            questionCode: "Q1",
            questionCodeSystem: "Custom",
            questionCodeDisplay: "Facility ID",
            linkId: "/G1/Q1",
            properties: {}, // need to remove this
            codingInstructions:
              "The NHSN-assigned facility ID will be autoentered by the computer.",
            codingInstructionsFormat: "text",
            codingInstructionsPlain:
              "The NHSN-assigned facility ID will be autoentered by the computer.",
          },
          "/G1/Q2": {
            type: "string",
            dataType: "ST",
            prefix: "2",
            title: "Summary Census #ID",
            codeList: [
              { code: "Q2", display: "Summary Census #ID", system: "Custom" },
            ],
            questionCode: "Q2",
            questionCodeSystem: "Custom",
            questionCodeDisplay: "Summary Census #ID",
            linkId: "/G1/Q2",
            readOnly: true,
            properties: {},
            codingInstructions: "Auto-generated by the computer.",
            codingInstructionsFormat: "text",
            codingInstructionsPlain: "Auto-generated by the computer.",
          },
          "/G1/Q3": {
            type: "string",
            dataType: "DT",
            format: "date",
            prefix: "3",
            title: "Effective Date",
            codeList: [
              { code: "Q3", display: "Effective Date", system: "Custom" },
            ],
            questionCode: "Q3",
            questionCodeSystem: "Custom",
            questionCodeDisplay: "Effective Date",
            linkId: "/G1/Q3",
            properties: {},
            codingInstructions:
              "Required. Select the date for which the recorded data was collected for the following questions.",
            codingInstructionsFormat: "text",
            codingInstructionsPlain:
              "Required. Select the date for which the recorded data was collected for the following questions.",
          },
          "/G1/Q4": {
            type: "array",
            dataType: "CNE",
            prefix: "4",
            title: "What pizza toppings would you like?",
            codeList: [
              {
                code: "Q4",
                display: "What pizza toppings would you like?",
                system: "Custom",
              },
            ],
            questionCode: "Q4",
            questionCodeSystem: "Custom",
            questionCodeDisplay: "What pizza toppings would you like?",
            linkId: "/G1/Q4",
            properties: {},
            codingInstructions: "Favorite toppings",
            codingInstructionsFormat: "text",
            codingInstructionsPlain: "Favorite toppings",
            items: { type: "string" },
          },
        },
      },
    },
  },
  fhirVersion: "R4",
};

export const qr = {
  resourceType: "QuestionnaireResponse",
  status: "completed",
  authored: "2021-09-06T16:12:39.748Z",
  item: [
    {
      linkId: "/G1",
      text: "Facility MetaData",
      item: [
        {
          linkId: "/G1/Q1",
          text: "Facility ID",
          answer: [{ valueString: "this fa" }],
        },
        [null],
      ],
    },
  ],
};
