name: Update Docker Hub Documentation

on:
  push:
    paths:
      - "docs/fhir-web-docker-deployment.md"
    branches:
      - main

jobs:
  update-docker-hub-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker Hub ReadMe
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: opensrp/web
          readme-filepath: docs/fhir-web-docker-deployment.md
